# -*- coding: utf-8 -*-
"""Bootcamp project (Data Analysis)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WKTV1hS2I2O8LtoLaDEwBjJeycq4_0gA
"""

import pandas as pd
import numpy as np

df = pd.DataFrame(pd.read_csv("/content/train (1).csv"))
df.head()

"""# New section"""

df.shape

df.isnull().sum()

drop_col = df.isnull().sum()[df.isnull().sum()> (35/100*df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index , axis = 1 , inplace = True)
df.isnull().sum()

df.fillna(df.mean() , inplace = True)
df.isnull().sum()

df["Embarked"].fillna("S" , inplace = True)

df.isnull().sum()

df.corr()

df["FamilySize"] = df["SibSp"] + df["Parch"]
df.drop(["SibSp" , "Parch"] , axis = 1 , inplace=True)
df.corr()

df['Alone'] = [0 if df["FamilySize"] [i] > 0 else 1 for i in df.index]
df.head()

df.groupby(["Alone"]) ["Survived"].mean()

df[["Alone","Fare"]].corr()

df["Sex"] = [ 0 if df["Sex"] [i] == "male" else 1 for i in df.index]
df.groupby(["Sex"])["Survived"].mean()

df.groupby(["Embarked"]) ["Survived"].mean()

"""**Conclusion**




* Female passengers were prioritized over man.
* People with high class or rich people has higher survival rate than others . The heirarchy ,ight have been followed while saving the passengers.
* Passengers travelling with their family have hugher survival rate.
* Passengers who boarded the ship at Cherbou, survived more in proportion than the others.




"""

